"""Metamorphic: reruns and reorderings must not change the final tree.

SPEC.md section 8 asks that reordering components, or rerunning the install, does
not change the result, and that an added foreign file can never be overwritten.
These properties are what make the installer safe to run repeatedly.
"""

from __future__ import annotations

import json
from pathlib import Path

from conftest import mesh_doc


def _install(installer, run_args, acs_root, adopter, pcm, cgm, oio, **over):
    return installer.run(run_args(acs_root, adopter, pcm, cgm, oio, **over))


def test_rerun_does_not_change_the_managed_files(
    installer, make_acs_root, make_adopter, make_checkouts, make_oio_checkout,
    stub_externals, run_args,
):
    stub_externals()
    adopter = make_adopter()
    pcm, cgm = make_checkouts()
    oio = make_oio_checkout()
    acs_root = make_acs_root()

    assert _install(installer, run_args, acs_root, adopter, pcm, cgm, oio) == 0
    assignment_before = (adopter / ".coord" / "assignment.json").read_bytes()
    manifest_before = (adopter / "stack-manifest.json").read_bytes()

    assert _install(installer, run_args, acs_root, adopter, pcm, cgm, oio) == 0
    assert (adopter / ".coord" / "assignment.json").read_bytes() == assignment_before
    assert (adopter / "stack-manifest.json").read_bytes() == manifest_before


def test_component_order_does_not_change_the_manifest(installer):
    mesh = mesh_doc()
    forward = installer.build_stack_manifest(mesh, "adopter-x")
    reversed_mesh = dict(mesh)
    reversed_mesh["requires"] = dict(reversed(list(mesh["requires"].items())))
    backward = installer.build_stack_manifest(reversed_mesh, "adopter-x")
    assert forward == backward


def test_an_added_foreign_file_is_never_overwritten(
    installer, make_acs_root, make_adopter, make_checkouts, make_oio_checkout,
    stub_externals, run_args,
):
    stub_externals()
    adopter = make_adopter()
    pcm, cgm = make_checkouts()
    oio = make_oio_checkout()
    acs_root = make_acs_root()
    assert _install(installer, run_args, acs_root, adopter, pcm, cgm, oio) == 0

    # An operator (or another tool) replaces a managed file with foreign content.
    foreign = json.dumps({"schema_version": "someone-else.v1", "pins": {}})
    (adopter / "stack-manifest.json").write_text(foreign, encoding="utf-8")

    assert _install(installer, run_args, acs_root, adopter, pcm, cgm, oio) == 1
    assert (adopter / "stack-manifest.json").read_text(encoding="utf-8") == foreign


def test_dry_run_leaves_the_tree_unchanged_then_real_run_matches(
    installer, make_acs_root, make_adopter, make_checkouts, make_oio_checkout,
    stub_externals, run_args,
):
    stub_externals()
    adopter = make_adopter()
    pcm, cgm = make_checkouts()
    oio = make_oio_checkout()
    acs_root = make_acs_root()

    assert _install(installer, run_args, acs_root, adopter, pcm, cgm, oio, dry_run=True) == 0
    assert not (adopter / ".coord").exists()
    assert not (adopter / "stack-manifest.json").exists()

    assert _install(installer, run_args, acs_root, adopter, pcm, cgm, oio) == 0
    assert (adopter / "stack-manifest.json").is_file()
    assert (adopter / ".coord" / "assignment.json").is_file()


def test_force_is_idempotent_for_an_unedited_file(
    installer, make_acs_root, make_adopter, make_checkouts, make_oio_checkout,
    stub_externals, run_args,
):
    """--force regenerates; for an unedited file the regenerated bytes are stable."""
    stub_externals()
    adopter = make_adopter()
    pcm, cgm = make_checkouts()
    oio = make_oio_checkout()
    acs_root = make_acs_root()

    assert _install(installer, run_args, acs_root, adopter, pcm, cgm, oio) == 0
    first = (adopter / "stack-manifest.json").read_bytes()
    assert _install(installer, run_args, acs_root, adopter, pcm, cgm, oio, force=True) == 0
    assert (adopter / "stack-manifest.json").read_bytes() == first
